table:
  name: token_operations
  schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - id
        - event_id
        - ledger
        - ledger_closed_at
        - contract_id
        - operation_type
        - from_address
        - to_address
        - amount
        - created_at
        - updated_at
      filter: {}
      allow_aggregations: true
