name: doc CI

on:
  push:
    branches: [main]
    paths:
      - 'doc/**'
      - '.github/workflows/doc-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'doc/**'
      - '.github/workflows/doc-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./doc

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: doc/node_modules
          key: ${{ runner.os }}-doc-node-${{ hashFiles('doc/package.json') }}
          restore-keys: |
            ${{ runner.os }}-doc-node-
      
      - name: Install dependencies
        run: npm install
      
      - name: Run typecheck
        run: npm run typecheck
      
      - name: Build project
        run: npm run build
